name: NodeJS with Gulp

on:
  push:
    branches: [ "master", "ci" ]

jobs:
  build-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
  build-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      
      
  gulp-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-node, build-ruby]
    steps:
      - run: gulp build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # The folder the action should deploy.
